services:
  api:
    container_name: api-go
    image: golang:1.18
    volumes:
      - .:/app/src
    ports:
      - 3000:3000
    command: tail -f "/dev/null"
    # develop:
    #   watch:
    #     - action: rebuild
    #       path: ./
# docker exec -it <ID> bash
